[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor]
blink_interval = 750
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "Underline"

[font]
size = 10

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono"
style = "monospace"

[font.offset]
x = 1
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.7
title = "Alacritty"

#[window.dimension]
#columns = 0
#lines = 0

[window.padding]
x = 0
y = 0
