#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V

#Xserver
xsetroot -cursor_name left_ptr &

#configs
bspc config border_width          3
bspc config window_gap            7

bspc config normal_border_color   "#4c566a"
bspc config focused_border_color  "#5e81ac"

bspc config click_to_focus        true


bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config top_padding           3


#autostart
picom & 
${HOME}/.fehbg &
polybar -c ${HOME}/.config/polybar/config.ini &

#rules



